---
# tasks file for Avisi.JIRA

- include: confluence.yml
  tags: [confluence, confluence-installatie]

- include: proxy.yml
  tags: [confluence, confluence-configuratie]

#Configure MYSQL backend
- include: mysql.yml
  when: system_config_database and db_type == "mysql"
  tags: [confluence, mysql-installatie]

#Configure Postgres backend
- include: postgres.yml
  when: system_config_database and db_type == "postgres"
  tags: [confluence, postgres-installatie]

- include: services.yml
  tags: [confluence, confluence-start]